// IMPORTANT: This file was auto-generated by the morebec/spectool program. Do not edit manually.

package customer

import (
	"time"
)

const CustomerRegisteredEventTypeName event.TypeName = "customer.registered"

// CustomerRegisteredEvent Records the fact that a customer was registered with the billing module.
type CustomerRegisteredEvent struct {

	// ID of the customer that was registered. This identifier is mapped to the customer's user account ID.
	CustomerID string `json:"customerId"`

	// Date and time at which the customer was registered.
	RegisteredAt time.Time `json:"registeredAt"`
}

func (c CustomerRegisteredEvent) TypeName() event.TypeName {
	return CustomerRegisteredEventTypeName
}

const RegisterCustomerCommandTypeName command.TypeName = "customer.register"

// RegisterCustomerCommand Registers a Customer
type RegisterCustomerCommand struct {

	// ID of the customer that was registered. This identifier is mapped to the customer's user account ID.
	CustomerID string `json:"customerId"`
}

func (c RegisterCustomerCommand) TypeName() command.TypeName {
	return RegisterCustomerCommandTypeName
}
