// IMPORTANT: This file was auto-generated by the morebec/spectool program. Do not edit manually.

package registration

import (
	"github.com/morebec/misas-go/misas/command"
)

const RenameUserCommandTypeName command.TypeName = "user_account_management.registration.register"

// RenameUserCommand Allows creating a user.
// In the system.
type RenameUserCommand struct {

	// Email address
	EmailAddress string `json:"emailAddress"`

	// ID of the user
	ID string `json:"id"`

	// New name of the user
	Name string `json:"name"`
}

func (c RenameUserCommand) TypeName() command.TypeName {
	return RenameUserCommandTypeName
}
